apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pingpong-backend-route
spec:
  parentRefs:
  - name: dwk-gateway # This is defined in ../cluster-management/gateway.yaml
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /pingpong
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: pingpong-backend-svc
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /pings
    backendRefs:
    - name: pingpong-backend-svc
      port: 80