apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: log-output-route
spec:
  parentRefs:
  - name: dwk-gateway # This is defined in ../cluster-management/gateway.yaml
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: log-output-svc
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /pingpong
    - path:
        type: PathPrefix
        value: /pings
    backendRefs:
    - name: pingpong-backend-svc
      port: 80