apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: Opaque
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Yce62W6OyMXYupbg,iv:RHJfiIxL4htPwsTWYS66B3Qyy38b7EX/TPvoJ138VQY=,tag:fMD0M5HyqxUxNZaYV6eTLg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:95HpjL9qzMPFBdLf,iv:mARNEiwHM8bXREdzb4CZV+PLHT+Dz7Gkqbbj5DBkeaE=,tag:hlNaJiwM8mSQZ74G/1n19A==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:iqzAtF4YAQIIXlAFmXeejZ9w2+FH9cSPTUB4k81+QH7V6bGKq/OcRGQwQZmBRZotrDqjTj9mqFsMVXRX,iv:Xhv/SUl6dC0mIlQuD32TkDXlnDSUCPfNezfMml2xQUA=,tag:bfphYSeF0DsnPGX+hepDLg==,type:str]
sops:
    age:
        - recipient: age1laaelp97m56cj7n90tv7rj2m28ckea0pq3excd4vj20yxqlssyjsuled6y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZTdnSkEwekpFeGN5a0pj
            cFpxeFgwS2ErSEQxZDd6UVlXd2pSd3hhbXh3CjAwNVdFd0JXNWVnc0ZWT09hb1Rz
            MStUQ3RybmtUemdtQmZlUU82ajJRYUUKLS0tIGw0TVBZdHN1aTRqQjZEcUU5TDdN
            SU9TbjZ4Q08zVnMyTElUMGFnWGlsUjgK/LbVIld+IN1X4dF+KH6PeCwFy0uBS/Gk
            he2r0wWA2GM31PlB6jK2mcBkZKTaSTYIsHYYM6IKXD/d2iQ9YJU9cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T14:55:17Z"
    mac: ENC[AES256_GCM,data:5Rv9rMYaLvf9XMowmeL3bpnrwaF2o1DdIyUJ6n6QVgs4QllTwA/I0QyHG2wuMQ+diKijUMcuzXZd3QyPwpFACAS0Bs/xW9ssiBmmoWWeo9oIGR4Ao0giQHzrv+qmwrrc8A4NQVxJ0nNbMIysS2QiQD3qoaO55BEJsEfSjIDioqE=,iv:ZbcEGCynOAL5739wDyugI3/v8zlW/K+4OOE5nKyIPqU=,tag:Gwhf3+RFjg37aCbnVTOZBw==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
